language: node_js
dist: trusty
node_js:
  - 7.2.0
before_script:
  - 'npm install -g npm@latest typescript ts-node concurrently nodemon'
  - 'npm install'
after_script:
  - 'mongod stop'
script:
  - 'npm run build'
  - 'npm run test'
env:
  - NODE_ENV=dev

sudo: false

services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
